// Group Names:
// Shuruq Baabdullah 1906284 VBR
// Rahaf Dawoud 1911088 VBR
// Elaf Yousef Aloufi 1911265
// Manar Mutlaq Altaiary 1906775
package CPIT305Project;

import javax.swing.ImageIcon;

public class physicalTherapy extends javax.swing.JFrame {

    /**
     * Creates new form physicalTherapy
     */
    public physicalTherapy() {
        initComponents();
        jLabel1.setIcon(new ImageIcon("src\\image\\background.png"));
        jLabel7.setIcon(new ImageIcon("src\\image\\back.png"));
        jLabel3.setIcon(new ImageIcon("src\\image\\doctor1.png"));
        jLabel5.setIcon(new ImageIcon("src\\image\\doctor2.png"));
        jLabel6.setIcon(new ImageIcon("src\\image\\doctor3.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        call1 = new javax.swing.JButton();
        book1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        book2 = new javax.swing.JButton();
        call2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        book3 = new javax.swing.JButton();
        call3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 100));

        call1.setBackground(new java.awt.Color(255, 255, 255));
        call1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        call1.setForeground(new java.awt.Color(153, 124, 168));
        call1.setText("Call");
        call1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        jPanel2.add(call1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 70, 30));

        book1.setBackground(new java.awt.Color(153, 124, 168));
        book1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        book1.setForeground(new java.awt.Color(245, 245, 245));
        book1.setText("Book");
        jPanel2.add(book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 350, 170));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 90));

        book2.setBackground(new java.awt.Color(153, 124, 168));
        book2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        book2.setForeground(new java.awt.Color(245, 245, 245));
        book2.setText("Book");
        jPanel3.add(book2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 80, -1));

        call2.setBackground(new java.awt.Color(255, 255, 255));
        call2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        call2.setForeground(new java.awt.Color(153, 124, 168));
        call2.setText("Call");
        call2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        jPanel3.add(call2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 70, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 350, 170));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 100));

        book3.setBackground(new java.awt.Color(153, 124, 168));
        book3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        book3.setForeground(new java.awt.Color(245, 245, 245));
        book3.setText("Book");
        jPanel4.add(book3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 80, -1));

        call3.setBackground(new java.awt.Color(255, 255, 255));
        call3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        call3.setForeground(new java.awt.Color(153, 124, 168));
        call3.setText("Call");
        call3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        jPanel4.add(call3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 70, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 350, 170));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(112, 112, 112));
        jLabel2.setText("Physical Therapy");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 60));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 414, 896));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new signin2().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(physicalTherapy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(physicalTherapy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(physicalTherapy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(physicalTherapy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new physicalTherapy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book1;
    private javax.swing.JButton book2;
    private javax.swing.JButton book3;
    private javax.swing.JButton call1;
    private javax.swing.JButton call2;
    private javax.swing.JButton call3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
