// Group Names:
// Shuruq Baabdullah 1906284 VBR
// Rahaf Dawoud 1911088 VBR
// Elaf Yousef Aloufi 1911265
// Manar Mutlaq Altaiary 1906775
package CPIT305Project;

import java.io.*;
import java.net.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class ServerChat1 extends javax.swing.JFrame {

    /**
     * Creates new form ServerChat
     */
    static String msgin = "";
    static DataInputStream din;
    static DataOutputStream dout;

    public ServerChat1() {
        initComponents();
        jLabel12.setIcon(new ImageIcon("src\\image\\back.png"));
        jLabel2.setIcon(new ImageIcon("src\\image\\small logo.png"));
        jLabel1.setIcon(new ImageIcon("src\\image\\chat.png"));
         try {
            ServerSocket ServerSocket = new ServerSocket(1201);
            Socket client = ServerSocket.accept();
            ClientHandelr ch = new ClientHandelr(client);
            ch.start();

            client = ServerSocket.accept();
            ClientHandelr ch2 = new ClientHandelr(client);
            ch2.start();
            //listining
            ArrayList<String> msgs;
            while (true) {
                msgs = ch.getReceivemsg();
                if (!msgs.isEmpty()) {
                    synchronized (msgs) {
                        for (int i = 0; i < msgs.size(); i++) {
                            ch2.sendmsg(msgs.get(i));
                        }
                        msgs.clear();
                    }

                }
                msgs = ch2.getReceivemsg();
                if (!msgs.isEmpty()) {
                    synchronized (msgs) {
                        for (int i = 0; i < msgs.size(); i++) {
                            ch.sendmsg(msgs.get(i));
                        }
                        msgs.clear();
                    }
                }

                try {
                    Thread.sleep(5);
                } catch (InterruptedException ex) {
                    System.out.println(ex.getMessage());
                }

            }// end of while

//                din = new DataInputStream(client.getInputStream());
//                dout = new DataOutputStream(client.getOutputStream());
//                while (true) {
//                    msg_area.setText("A new Client has connected");
//                    msgin = din.readUTF();
//                    msg_area.setText(msg_area.getText().trim() + "\nClient: " + msgin);
//                    if (msgin.equalsIgnoreCase("exit")) {
//                        break;
//                    }
//                    din.close();
//                    dout.close();
//                }
//
//            }
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        msg_send = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 110, 430, 550));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(112, 112, 112));
        jLabel6.setText("Support");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msg_send.setBackground(new java.awt.Color(153, 124, 168));
        msg_send.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        msg_send.setForeground(new java.awt.Color(245, 245, 245));
        msg_send.setText("send");
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });
        jPanel3.add(msg_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 760, -1, 40));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 15, 140, 80));

        msg_area.setColumns(20);
        msg_area.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        msg_area.setRows(5);
        msg_area.setBorder(null);
        jScrollPane1.setViewportView(msg_area);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 410, 640));

        msg_text.setForeground(new java.awt.Color(204, 204, 204));
        msg_text.setText("type a message...");
        msg_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_textActionPerformed(evt);
            }
        });
        jPanel3.add(msg_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 320, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_sendActionPerformed
        try {
            String msgout = "";
            msgout = msg_text.getText().trim();
            dout.writeUTF(msgout);
            msg_area.setText("Server: " + msg_text.getText().trim());
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_msg_sendActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void msg_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msg_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerChat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerChat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerChat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerChat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ServerChat1().setVisible(true);
            }
        });

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea msg_area;
    private static javax.swing.JButton msg_send;
    private javax.swing.JTextField msg_text;
    // End of variables declaration//GEN-END:variables

}
